name: OF2206-GCC13
defaults:
  run:
    shell: bash -o pipefail -i {0}
on:
  push

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/foamscience/jammy-openfoam:v2206-gcc13
      options: --user openfoam
      env:
        CATCH_TIMEOUT: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile and Test
        run: |
          sudo apt install -y libopm-dev
          source /usr/lib/openfoam/openfoam2206/etc/bashrc
          mkdir -p $FOAM_USER_LIBBIN
          export FOAM_FOAMUT=/tmp/foamut
          git clone https://github.com/FoamScience/foamUT $FOAM_FOAMUT
          sed -i 's/mpirun/mpirun --oversubscribe/g' $FOAM_FOAMUT/Alltest
          ln -s "$PWD" "$FOAM_FOAMUT/tests/openmp"
          cd $FOAM_FOAMUT || exit 1
          rm -rf tests/exampleTests
          ./Alltest --no-parallel "$@"
